name: DeathCounter
version: '${project.version}'
main: net.kunkun2121.deathcounter.deathcounter.DeathCounter
api-version: 1.18

commands:
  deathcounter:
    usage: /<command>
    description: can fly